require('dotenv').config()

let {
    SALT_ROUND_NUMBER,
    BCRYPT_WORK_FACTOR,
    BCRYPT_MAX_BYTES,
    TOKEN_EXPIRATION_TIME,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET
} = process.env

SALT_ROUND_NUMBER = parseInt(SALT_ROUND_NUMBER)
BCRYPT_WORK_FACTOR = parseInt(BCRYPT_WORK_FACTOR)
BCRYPT_MAX_BYTES = parseInt(BCRYPT_MAX_BYTES)
TOKEN_EXPIRATION_TIME = parseInt(TOKEN_EXPIRATION_TIME)


module.exports = {
    SALT_ROUND_NUMBER,
    BCRYPT_WORK_FACTOR,
    BCRYPT_MAX_BYTES,
    TOKEN_EXPIRATION_TIME,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET
}